name: Validate Extension

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Setup Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: '3.9.13'

      - name: Setup Virtual Environment
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -c "import sys; print('\n'.join(sys.path))"

      - name: Install robofontExtensionBundle package
        run: |
          source .venv/bin/activate
          pip install git+https://github.com/typemytype/extensionBundle
